### PR TITLE
Remove incorrect commas

### PR DESCRIPTION
**Pull request by md2perpe**
Those commas seem misplaced. Without them the parameter list makes more sense.

### CODE REVIEW

**Comment by luohuang** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到。
 
谢谢！

**Comment by md2perpe** [comment]
There's no need to be nasty. I was blinded by the lines looking like declarations and missed that each line consisted of two separate arguments to a macro. Sorry for disturbing.

**Comment by tijko** [comment]
Didn't mean to come off that way, I guess my inner Torvald took over.  No harm no foul, happy hacking!

**Comment by tijko** [comment]
@luohuang I would move to close as this is wrong and just based off a mis-understanding.

**Comment by 0xAX** [comment]
so I am closing this one :)

**Pull request closed without merging**
