### PR TITLE
Improve sentence structure and fix some typos

### PR DESCRIPTION
**Pull request by dnadolny**
Various small spelling/grammar/sentence structure/syntax changes to the two memory management pages.

### CODE REVIEW

**Comment by 0xAX** [comment]
Thank you @davydovanton

**Comment by davydovanton** [comment]
@0xAX i think you mistyped with @dnadolny name :wink:

**Comment by dnadolny** [comment]
No problem - dnadolny, davydovanton, the keys are like right next to each other :)

**Comment by 0xAX** [comment]
@davydovanton Yes :) Github autocompletion made it, not me :)

**Pull request merged**
