### PR TITLE
对how_kernel_compiled.md 的翻译

### PR DESCRIPTION
**Pull request by oska874**
Translate how_kernel_compiled.md into Simple Chinese。

### CODE REVIEW

**Comment by mudongliang** [comment]
Are you sure to add Chinese versin into this repo? 
I think we should create a new repo, and add it there.

**Comment by oska874** [comment]
I think this could be in same repo. Because here maybe only one translated article, and the different language version of one article located in one repo is friendly to different language people。

**Comment by mudongliang** [comment]
If you consist on this style ,I recommend this repo : [progit] (https://github.com/progit/progit)
One language , one directory!

**Comment by wxy** [comment]
Single page only , keep it in the directory is OK. example : https://github.com/jlevy/the-art-of-command-line

**Comment by oska874** [comment]
@mudongliang if create a new directory and put only one file, this file will feel lonely.Put the chinese and english together.

**Comment by mudongliang** [comment]
@wxy Single page only is good for that file is one or several files without directory structure!
Once there are complex directory structure， it is not good.
@oska874 if you predict there will only two languages, it doesn't matter. But if the language is more , the directory structure will be a mass.
I think the solution should be :
- one language , one repo;
- one language , one directory in the repo;

**Comment by 0xAX** [comment]
Hello all, The better way will be to put translations on other languages to separate repo.

@oska874 There is already repo with Chinese translation, started by @xinqui - https://github.com/xinqiu/linux-insides. I think you can connect with him and send PR there and I'll add link to the README about this repo

**Comment by mudongliang** [comment]
:+1:

**Pull request closed without merging**
