### PR TITLE
 Finish fixing broken links related with Theory, Data structure, Misc and so on

### PR DESCRIPTION
**Pull request by mudongliang**
First, I have almost finished fixing all the broken links with keyword - "0xax". There is only 1 broken link with keyword "0xax" in the repo - http://0xax.github.io/categories/assembly/. I don't know how to modify it.

Then for some "http" links in the gitbook, I may miss. However, I could write one script to modify all the "http://0xax.gitbook.io/..." to "https://0xax.gitbook.io/..." we both prefer.

Finally, all the things will return back to normal.

### CODE REVIEW

**Comment by 0xAX** [comment]
Hello @mudongliang,

> First, I have almost finished fixing all the broken links with keyword - "0xax". There is only 1 broken link with keyword "0xax" in the repo - http://0xax.github.io/categories/assembly/. I don't know how to modify it.

Seems it just should be `https`. Will fix it after this PR.

> Then for some "http" links in the gitbook, I may miss. However, I could write one script to modify all the "http://0xax.gitbook.io/..." to "https://0xax.gitbook.io/..." we both prefer.

Yes it should be pretty easy to do. I will try to find time to do it on these weekends.

> Finally, all the things will return back to normal.
:+1: :+1: :+1:

**Comment by 0xAX** [comment]
Now it should be fixed in the last commit https://github.com/0xAX/linux-insides/commit/264d9101826946ee391922e812a2840433acc836

**Comment by 0xAX** [comment]
@mudongliang btw maybe we should add travis-ci or something like this to run the script after commits to catch wrong/dead links? 

What do you think about this?

**Comment by mudongliang** [comment]
Good idea.

**Pull request merged**
