### PR TITLE
Interrupts/linux-interrupts-5.md: fix content

### PR DESCRIPTION
**Pull request by GIHOLee**
fix content：`SIGILL` for overflow exception -> `SIGILL` for the invalid opcode

### CODE REVIEW

**Comment by GIHOLee** [comment]
@initBasti Sorry, I want to give you a like but accidentally clicked the icon of "Re request review". (This is my first pull requests and Unskilled)

**Comment by initBasti** [comment]
> @initBasti Sorry, I want to give you a like but accidentally clicked the icon of "Re request review". (This is my first pull requests and Unskilled)

@GIHOLee 
Hey, just wanted to ask if you still want to finish this pull request?

**Comment by GIHOLee** [comment]
> > @initBasti Sorry, I want to give you a like but accidentally clicked the icon of "Re request review". (This is my first pull requests and Unskilled)
> 
> @GIHOLee
> Hey, just wanted to ask if you still want to finish this pull request?

@initBasti Hi, maybe this change is not necessary, should I close it?

**Comment by initBasti** [comment]
> > > @initBasti Sorry, I want to give you a like but accidentally clicked the icon of "Re request review". (This is my first pull requests and Unskilled) 
> > 
> > @GIHOLee
> > Hey, I just wanted to ask if you still want to finish this pull request?
> 
> @initBasti Hi, maybe this change is not necessary, should I close it?

@GIHOLee I think the change is fine, I just think a small change to the grammar and word choice would improve it. That's why I requested a small change. If you apply that small change I'm happy to merge it, as I don't have to apply a new patch above it afterward.

**Comment by GIHOLee** [comment]
@initBasti Okay, I apply some small change of grammar as you telled me. And create a new pr.

**Pull request closed without merging**
