### PR TITLE
Provide epub, pdf and mobi formats

### PR DESCRIPTION
**Pull request by ozkanonur**
Epub, pdf and mobi formats are generated from the latest master branch.

On branch provide-book-formats
Changes to be committed:
	new file:   Assets/linux-kernel-insides.epub
	new file:   Assets/linux-kernel-insides.mobi
	new file:   Assets/linux-kernel-insides.pdf
	deleted:    Scripts/LinuxKernelInsides.pdf
	modified:   Scripts/latex.sh
	modified:   contributors.md

Signed-off-by: Onur Ozkan <work@onurozkan.dev>

### CODE REVIEW

**Comment by luohuang** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到。
 
谢谢！

**Comment by 0xAX** [comment]
That is probably not the best way to store them in the repository as they could be easily unsynchronized with md content

**Comment by 0xAX** [comment]
I will add link to the https://github.com/GitbookIO/gitbook/blob/master/docs/ebook.md in README.md, let's stay with it for now

**Comment by siddhpant** [comment]
> That is probably not the best way to store them in the repository as they could be easily unsynchronized with md content

I agree. A better way would be creating a release on push using GitHub actions.

**Pull request closed without merging**
