### PR TITLE
feat: Fill in the details of __PAGE_OFFSET

### PR DESCRIPTION
**Pull request by Mutated1994**

### CODE REVIEW

**Comment by Mutated1994** [comment]
I‘m trying to submit a PR once per day.

KEEP GOING!

**Review by initBasti — CHANGES_REQUESTED** [review]
Hey, thank you for the patch.
I would change the following sentences:

s/
The `early_recursion_flag` locates in the same assembly file as the `early_idt_handler_common` symbol like the following:/
The `early_recursion_flag` is defined in the same assembly file as the `early_idt_handler_common` symbol as follows:/

s/
and you can note that the `UL` tells the compiler that they are not of type int, but unsigned long./
The suffix `UL` forces the page offset to be a unsigned long data type./

**Comment by Mutated1994** [comment]
> Hey, thank you for the patch.
> I would change the following sentences:
> 
> s/
> The `early_recursion_flag` locates in the same assembly file as the `early_idt_handler_common` symbol like the following:/
> The `early_recursion_flag` is defined in the same assembly file as the `early_idt_handler_common` symbol as follows:/
> 
> s/
> and you can note that the `UL` tells the compiler that they are not of type int, but unsigned long./
> The suffix `UL` forces the page offset to be a unsigned long data type./

Gotcha!

**Review by initBasti — APPROVED** [review]
Cool thanks for the fast adjustment.

**Comment by Mutated1994** [comment]
> Cool thanks for the fast adjustment.

It's my pleasure.

**Pull request merged**
